specify the `minWorkers` value to avoid conflicts
Was getting this in CI:
```
RangeError: options.minThreads and options.maxThreads must not conflict
 ❯ new Tinypool ../../node_modules/.pnpm/tinypool@1.0.2/node_modules/tinypool/dist/index.js:980:13
 ❯ createForksPool ../../node_modules/.pnpm/vitest@2.1.8_@types+node@20.16.0/node_modules/vitest/dist/chunks/resolveConfig.RxKrDli4.js:6755:16
 ❯ forks ../../node_modules/.pnpm/vitest@2.1.8_@types+node@20.16.0/node_modules/vitest/dist/chunks/resolveConfig.RxKrDli4.js:7663:20
```