fix(module-scan): work around error in start script
`pnpm start` was failing with this:
```
../../libs/hmpb-interpreter/dist/src/getVotesFromMarks.js:40:17 - error TS2578: Unused '@ts-expect-error' directive.

40                 // @ts-expect-error - `mark` is `never` because the types say there are no other options
```